CREATE DEFINER=`root`@`localhost` PROCEDURE `datosEncuestas`()
BEGIN
	DECLARE i INT;
    DECLARE ii INT;
    DROP TABLE IF EXISTS ENCUESTAS;
    
    CREATE TABLE ENCUESTAS(
		IDENCUESTA INT NOT NULL auto_increment PRIMARY KEY,
        SONIDO INT NOT NULL,
        IMAGEN INT NOT NULL,
        USABILIDAD INT NOT NULL,
        CODPROV CHAR(2),
        FOREIGN KEY (CODPROV) REFERENCES PROVINCIA(CODPROV)
    );
    
    SET i=0;
    START TRANSACTION;
    WHILE i<52 DO
		SET i=i+1;
        SET ii=0;
        START TRANSACTION;
        WHILE ii<10 DO
			SET ii=ii+1;
            INSERT INTO ENCUESTAS VALUES (NULL,(RAND()*10),(RAND()*10),(RAND()*10),LPAD(i,2,'0'));
		END WHILE;
	END WHILE;
    COMMIT;
END