DROP DATABASE IF EXISTS ENCUESTAS;
CREATE DATABASE ENCUESTAS;
USE ENCUESTAS;

CREATE TABLE PROVINCIA(
	CODPROV CHAR(2) PRIMARY KEY,
    NOMBRE_PROVINCIA VARCHAR(30)
);

INSERT INTO PROVINCIA VALUES ('01', 'Araba/Álava');
INSERT INTO PROVINCIA VALUES ('02', 'Albacete');
INSERT INTO PROVINCIA VALUES ('03', 'Alacant/Alicante');
INSERT INTO PROVINCIA VALUES ('04', 'Almería');
INSERT INTO PROVINCIA VALUES ('05', 'Ávila');
INSERT INTO PROVINCIA VALUES ('06', 'Badajoz');
INSERT INTO PROVINCIA VALUES ('07', 'Illes Balears');
INSERT INTO PROVINCIA VALUES ('08', 'Barcelona');
INSERT INTO PROVINCIA VALUES ('09', 'Burgos');
INSERT INTO PROVINCIA VALUES ('10', 'Cáceres');
INSERT INTO PROVINCIA VALUES ('11', 'Cádiz');
INSERT INTO PROVINCIA VALUES ('12', 'Castelló/Castellón');
INSERT INTO PROVINCIA VALUES ('13', 'Ciudad Real');
INSERT INTO PROVINCIA VALUES ('14', 'Córdoba');
INSERT INTO PROVINCIA VALUES ('15', 'A Coruña');
INSERT INTO PROVINCIA VALUES ('16', 'Cuenca');
INSERT INTO PROVINCIA VALUES ('17', 'Girona');
INSERT INTO PROVINCIA VALUES ('18', 'Granada');
INSERT INTO PROVINCIA VALUES ('19', 'Guadalajara');
INSERT INTO PROVINCIA VALUES ('20', 'Gipuzkoa');
INSERT INTO PROVINCIA VALUES ('21', 'Huelva');
INSERT INTO PROVINCIA VALUES ('22', 'Huesca');
INSERT INTO PROVINCIA VALUES ('23', 'Jaén');
INSERT INTO PROVINCIA VALUES ('24', 'León');
INSERT INTO PROVINCIA VALUES ('25', 'Lleida');
INSERT INTO PROVINCIA VALUES ('26', 'La Rioja');
INSERT INTO PROVINCIA VALUES ('27', 'Lugo');
INSERT INTO PROVINCIA VALUES ('28', 'Madrid');
INSERT INTO PROVINCIA VALUES ('29', 'Málaga');
INSERT INTO PROVINCIA VALUES ('30', 'Murcia');
INSERT INTO PROVINCIA VALUES ('31', 'Navarra');
INSERT INTO PROVINCIA VALUES ('32', 'Ourense');
INSERT INTO PROVINCIA VALUES ('33', 'Asturias');
INSERT INTO PROVINCIA VALUES ('34', 'Palencia');
INSERT INTO PROVINCIA VALUES ('35', 'Las Palmas');
INSERT INTO PROVINCIA VALUES ('36', 'Pontevedra');
INSERT INTO PROVINCIA VALUES ('37', 'Salamanca');
INSERT INTO PROVINCIA VALUES ('38', 'Santa Cruz de Tenerife');
INSERT INTO PROVINCIA VALUES ('39', 'Cantabria');
INSERT INTO PROVINCIA VALUES ('40', 'Segovia');
INSERT INTO PROVINCIA VALUES ('41', 'Sevilla');
INSERT INTO PROVINCIA VALUES ('42', 'Soria');
INSERT INTO PROVINCIA VALUES ('43', 'Tarragona');
INSERT INTO PROVINCIA VALUES ('44', 'Teruel');
INSERT INTO PROVINCIA VALUES ('45', 'Toledo');
INSERT INTO PROVINCIA VALUES ('46', 'València/Valencia');
INSERT INTO PROVINCIA VALUES ('47', 'Valladolid');
INSERT INTO PROVINCIA VALUES ('48', 'Bizkaia');
INSERT INTO PROVINCIA VALUES ('49', 'Zamora');
INSERT INTO PROVINCIA VALUES ('50', 'Zaragoza');
INSERT INTO PROVINCIA VALUES ('51', 'Ceuta');
INSERT INTO PROVINCIA VALUES ('52', 'Melilla');

-- 4 
SELECT *,(SONIDO+IMAGEN+USABILIDAD)/3 AS MEDIA FROM ENCUESTAS;

-- 5
SELECT NOMBRE_PROVINCIA,ENCUESTAS.*,(SONIDO+IMAGEN+USABILIDAD)/3 AS MEDIA FROM ENCUESTAS
INNER JOIN PROVINCIA
ON ENCUESTAS.CODPROV=PROVINCIA.CODPROV;

-- 6
SELECT PROVINCIA.CODPROV, NOMBRE_PROVINCIA, AVG(SONIDO) AS MEDIA_SONINDO, AVG(IMAGEN) AS MEDIA_IMAGEN, AVG(USABILIDAD) AS MEDIA_USABILIDAD
FROM PROVINCIA
INNER JOIN ENCUESTAS
ON PROVINCIA.CODPROV=ENCUESTAS.CODPROV
GROUP BY NOMBRE_PROVINCIA;

-- 7
SELECT PROVINCIA.CODPROV, NOMBRE_PROVINCIA, AVG(SONIDO) AS MEDIA_SONINDO, AVG(IMAGEN) AS MEDIA_IMAGEN, AVG(USABILIDAD) AS MEDIA_USABILIDAD,
(AVG(SONIDO)+AVG(IMAGEN)+AVG(USABILIDAD))/3 AS MEDIA
FROM PROVINCIA
INNER JOIN ENCUESTAS
ON PROVINCIA.CODPROV=ENCUESTAS.CODPROV
GROUP BY NOMBRE_PROVINCIA;

-- 8
SELECT PROVINCIA.CODPROV, NOMBRE_PROVINCIA, AVG(SONIDO) AS MEDIA_SONINDO, AVG(IMAGEN) AS MEDIA_IMAGEN, AVG(USABILIDAD) AS MEDIA_USABILIDAD,
(AVG(SONIDO)+AVG(IMAGEN)+AVG(USABILIDAD))/3 AS MEDIA
FROM PROVINCIA
INNER JOIN ENCUESTAS
ON PROVINCIA.CODPROV=ENCUESTAS.CODPROV
GROUP BY NOMBRE_PROVINCIA
HAVING MEDIA<6;

-- 9 

SELECT IDENCUESTA,provincia.NOMBRE_PROVINCIA,provincia.CODPROV,SONIDO,IMAGEN,USABILIDAD,(SONIDO+IMAGEN+USABILIDAD)/3 AS MEDIA 
FROM ENCUESTAS
INNER JOIN provincia
on encuestas.CODPROV=provincia.CODPROV
GROUP BY IDENCUESTA
ORDER BY (SONIDO+IMAGEN+USABILIDAD)/3 DESC
LIMIT 1;

-- 10
select encuestas.valoracion(1, 3, 3);

SELECT IDENCUESTA,NOMBRE_PROVINCIA,encuestas.CODPROV,encuestas.SONIDO,encuestas.IMAGEN,encuestas.USABILIDAD, 
valoracion(SONIDO,IMAGEN,USABILIDAD) AS resultado FROM ENCUESTAS
INNER JOIN PROVINCIA
on ENCUESTAS.CODPROV=PROVINCIA.CODPROV;

SELECT count(*),valoracion(SONIDO,IMAGEN,USABILIDAD) AS resultado FROM encuestas
GROUP BY resultado;


-- 1 SEGUNDA PARTE

 CREATE TABLE ENCUESTA_OLD(
	IDENCUESTA INT NOT NULL auto_increment PRIMARY KEY,
	SONIDO INT NOT NULL,
	IMAGEN INT NOT NULL,
	USABILIDAD INT NOT NULL,
	CODPROV CHAR(2),
	FOREIGN KEY (CODPROV) REFERENCES PROVINCIA(CODPROV)
);

SET sql_safe_updates=0;
DELETE FROM ENCUESTAS WHERE IDENCUESTA=2;
SET sql_safe_updates=1;

SELECT * FROM ENCUESTA_OLD;
