
create view resumen as 
SELECT PROVINCIA.CODPROV, NOMBRE_PROVINCIA, AVG(SONIDO) AS MEDIA_SONINDO, AVG(IMAGEN) AS MEDIA_IMAGEN, AVG(USABILIDAD) AS MEDIA_USABILIDAD,
(AVG(SONIDO)+AVG(IMAGEN)+AVG(USABILIDAD))/3 AS MEDIA
FROM PROVINCIA
INNER JOIN ENCUESTAS
ON PROVINCIA.CODPROV=ENCUESTAS.CODPROV
GROUP BY NOMBRE_PROVINCIA;